name: AWS Lambda Build, Test, Deploy with SAM
on:
  push:
    branches: [ main ]

env:
  S3_BUCKET: xxx 
  REGION: xxx 

jobs:
  validate-test:
    runs-on: ubuntu-latest
    name: Setup 
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: aws-actions/setup-sam@v1
        run: |
          sudo apt-get update
          pip3 install pytest

      - name: Configure Creds and Build, Test, Validate
        id: creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }}

        run: |
          sam validate
          sam build
          python3 pytest -vvv


  build-deploy:
    needs: validate-test
    runs-on: ubuntu-latest
    name: Deploy Lambda 
    steps:
      - run: |
          sam build --use-container
          sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name sample \\
          --s3-bucket $(( env.S3_BUCKET}} --region $(( env.REGION}}

